<?php
echo <<<XML
<dip_command>
<command_return>SUCCESS</command_return>
<return_data>
<total_pages>20</total_pages>
<row>
<row_id>1</row_id>
<table>table1</table>
<owner>me</owner>
<scn>21524655</scn>
<operation>delete</operation>
<timestamp>256566</timestamp>
<backup_table>batable</backup_table>
</row>
<row>
<row_id>1</row_id>
<table>table1</table>
<owner>me</owner>
<scn>21524655</scn>
<operation>delete</operation>
<timestamp>256566</timestamp>
<backup_table>batable</backup_table>
</row>
<row>
<row_id>1</row_id>
<table>table1</table>
<owner>me</owner>
<scn>21524655</scn>
<operation>delete</operation>
<timestamp>256566</timestamp>
<backup_table>batable</backup_table>
</row>
<row>
<row_id>1</row_id>
<table>table1</table>
<owner>me</owner>
<scn>21524655</scn>
<operation>delete</operation>
<timestamp>256566</timestamp>
<backup_table>batable</backup_table>
</row>
</return_data>
</dip_command>
XML
;