<?php
	echo <<<XML
<dip_command>
  <command_return>SUCCESS</command_return>
  <return_data>
    <group>
      <name>hello_group</name>
      <captures>
        <capture>
          <name>cap1</name>
          <thread>1556</thread>
          <db_name>xxxx</db_name>
          <status>running</status>         
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1566</work_scn>
          <work_scn_time>154165454</work_scn_time>
        </capture>   
         <capture>
          <name>cap2</name>
          <thread>1551</thread>
          <db_name>xxxx</db_name>
          <status>running</status>         
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1566</work_scn>
          <work_scn_time>154165454</work_scn_time>
        </capture>                         
        <simulator>
          <thread>1551</thread>
          <name>simulator</name>
          <db_name>xxxx</db_name>
          <status>sss</status>
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1151</work_scn>
          <work_scn_time>216456545</work_scn_time>
        </simulator>
      </captures> 
      <servers>
        <server>
          <name>server1</name>
          <db_name>xxxx</db_name>
          <thread>1551</thread>
          <status>running</status>
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>15555</work_scn>
          <work_scn_time>21565455</work_scn_time>
        </server>
      </servers>
    </group>
    <group>
      <name>A</name>
      <captures>
        <capture>
          <name>cap1</name>
          <thread>1551</thread>
          <db_name>xxxx</db_name>
          <status>xxx</status>         
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1566</work_scn>
          <work_scn_time>154165454</work_scn_time>
        </capture>   
         <capture>
          <name>cap2</name>
          <thread>1551</thread>
          <db_name>xxxx</db_name>
          <status>running</status>         
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1566</work_scn>
          <work_scn_time>154165454</work_scn_time>
        </capture>                         
        <simulator>
          <thread>1551</thread>
          <name>simulator</name>
          <db_name>xxxx</db_name>
          <status>sss</status>
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1151</work_scn>
          <work_scn_time>216456545</work_scn_time>
        </simulator>
      </captures> 
      <servers>
        <server>
          <name>server1</name>
          <db_name>xxxx</db_name>
          <thread>1551</thread>
          <status>running</status>
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>15555</work_scn>
          <work_scn_time>21565455</work_scn_time>
        </server>
      </servers>
    </group>
    <group>
      <name>A</name>
      <captures>
        <capture>
          <name>cap1</name>
          <thread>1551</thread>
          <db_name>xxxx</db_name>
          <status>xxx</status>         
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1566</work_scn>
          <work_scn_time>154165454</work_scn_time>
        </capture>   
         <capture>
          <name>cap2</name>
          <thread>1551</thread>
          <db_name>xxxx</db_name>
          <status>running</status>         
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1566</work_scn>
          <work_scn_time>154165454</work_scn_time>
        </capture>                         
        <simulator>
          <thread>1551</thread>
          <name>simulator</name>
          <db_name>xxxx</db_name>
          <status>sss</status>
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1151</work_scn>
          <work_scn_time>216456545</work_scn_time>
        </simulator>
      </captures> 
      <servers>
        <server>
          <name>server1</name>
          <db_name>xxxx</db_name>
          <thread>1551</thread>
          <status>running</status>
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>15555</work_scn>
          <work_scn_time>21565455</work_scn_time>
        </server>
      </servers>
    </group>
    <group>
      <name>A</name>
      <captures>
        <capture>
          <name>cap1</name>
          <thread>1551</thread>
          <db_name>xxxx</db_name>
          <status>xxx</status>         
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1566</work_scn>
          <work_scn_time>154165454</work_scn_time>
        </capture>   
         <capture>
          <name>cap2</name>
          <thread>1551</thread>
          <db_name>xxxx</db_name>
          <status>running</status>         
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1566</work_scn>
          <work_scn_time>154165454</work_scn_time>
        </capture>                         
        <simulator>
          <thread>1551</thread>
          <name>simulator</name>
          <db_name>xxxx</db_name>
          <status>sss</status>
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1151</work_scn>
          <work_scn_time>216456545</work_scn_time>
        </simulator>
      </captures> 
      <servers>
        <server>
          <name>server1</name>
          <db_name>xxxx</db_name>
          <thread>1551</thread>
          <status>running</status>
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>15555</work_scn>
          <work_scn_time>21565455</work_scn_time>
        </server>
      </servers>
    </group>
    <group>
      <name>A</name>
      <captures>
        <capture>
          <name>cap1</name>
          <thread>1551</thread>
          <db_name>xxxx</db_name>
          <status>xxx</status>         
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1566</work_scn>
          <work_scn_time>154165454</work_scn_time>
        </capture>   
         <capture>
          <name>cap2</name>
          <thread>1551</thread>
          <db_name>xxxx</db_name>
          <status>running</status>         
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1566</work_scn>
          <work_scn_time>154165454</work_scn_time>
        </capture>                         
        <simulator>
          <thread>1551</thread>
          <name>simulator</name>
          <db_name>xxxx</db_name>
          <status>sss</status>
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>1151</work_scn>
          <work_scn_time>216456545</work_scn_time>
        </simulator>
      </captures> 
      <servers>
        <server>
          <name>server1</name>
          <db_name>xxxx</db_name>
          <thread>1551</thread>
          <status>running</status>
          <start_time>2012-12-11:10:00:0</start_time>
          <work_scn>15555</work_scn>
          <work_scn_time>21565455</work_scn_time>
        </server>
      </servers>
    </group>
  </return_data>
</dip_command>
XML
;